### ISSUE TITLE
Probability to using Pix2Seq for Page Stream Segmentation

### ISSUE THREAD

**Issue by pu2is** [gaopengcuhk/Unofficial-Pix2Seq#3]
Hi,

i begin my research on Page Stream Segmentation for a short time. PSS is a method to split the scanned documents automatically. Do you think it is possible to use Pix2Seq for this problem? Because i have seen on the paper, it could be used to solve imagine caption.

best regards,
Chao

**Comment by gaopengcuhk** [comment]
I am unfamiliar with PSS. If you can transform the annotation into a discrete token, Pix2seq could be a potential apparoch.
