### ISSUE TITLE
How to inference in custom dataset？

### ISSUE THREAD

**Issue by YunLongPan** [gaopengcuhk/Unofficial-Pix2Seq#4]
I have a problem with the predict.py code of DETR
-------------------------------------------------------------------------------------------------
(detr) D:\Pix2Seq-main>python predict.py
dict_keys(['model', 'optimizer', 'lr_scheduler', 'epoch', 'args'])
Traceback (most recent call last):
  File "predict.py", line 110, in <module>
    scores, boxes = predict(im, model, transform)
  File "predict.py", line 85, in predict
    outputs = model(data)
  File "D:\Anaconda\envs\detr\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'sequence'

**Comment by gaopengcuhk** [comment]
We will add a predict.py demo in the future. Stay finetuned.

**Comment by gaopengcuhk** [comment]
We will add a predict.py demo in the future. Stay tuned.

**Comment by gaopengcuhk** [comment]
We upload predict.py and also three demo object detection images. Thanks so much for your suggestion.
